### ISSUE TITLE
`impl AsRef<std::path::Path> for Utf8NativePath`

### ISSUE THREAD

**Issue by Nemo157** [chipsenkbeil/typed-path#12]
I have a tool where I'm having to deal with both unix and native paths together (and converting between them). When interacting with the filesystem I want to obviously only use the native paths, but since I'm having to go via `.as_str()` there's nothing actually enforcing this. If there was the `AsRef<Path>` impl for only the correct encoding then I would have some implicit checks that I'm using the correct variant.

**Comment by chipsenkbeil** [comment]
@Nemo157 added `AsRef<Path>` for `Utf8NativePath` and `Utf8NativePathBuf` alongside `From<Utf8NativePathBuf>` for `PathBuf`. You can find this included in the newly-published `0.4.1` of the crate.

Let me know if you need anything else!
