### ISSUE TITLE
Utf8UnixPath as_str() and to_string()

### ISSUE THREAD

**Issue by hjmallon** [chipsenkbeil/typed-path#7]
This could just be a bug on my side, but I found it confusing that `Utf8UnixPath::new("my/path").to_string()` has `"` around the path, when none of the other methods (`as_str(), into_string()` etc) do.

std::path::Path doesn't seem to have the same behaviour (it seems to never add `"`s)

**Comment by chipsenkbeil** [comment]
Sounds like a bug to me! I'll look into why and get a fix out.

**Comment by chipsenkbeil** [comment]
> Thanks again! 0.3.2 fixes the issue for me. Also thanks for such speedy responses.

@hjmallon thanks for finding and reporting these issues with a clear problem and expectation :) I wrote this library to solve a need for myself, and it's good to see some of the rough edges getting worked out!
